steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile', '-t', 'gcr.io/$PROJECT_ID/sales-prediction-api-minimal', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sales-prediction-api-minimal']
images:
  - 'gcr.io/$PROJECT_ID/sales-prediction-api-minimal'
